version: "3"
services:
  nginx:
    image: lihn1011/nginx:0.6
    container_name: pha_nginx
    hostname: pha_nginx
    command: /bin/bash -c "while true;nginx -g 'daemon off;';do sleep 1 ; done"
    volumes:
      - ./data/nginx/config/default:/etc/nginx/sites-enabled/default
      - ./data/nginx/src/:/var/www/html/
    ports:
      - "80:80"
  mysql:
    container_name: mysql
    image: lihn1011/mysql:0.3
    volumes:
        - ./data/mysql/:/var/lib/mysql/
    restart: always
    command: mysqld --sql-mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
    expose:
        - 3306
    ports:
        - "9981:3306"
  rest:
    image: lihn1011/rest:0.5
    container_name: rest
    hostname: rest
    command: /bin/bash -c "while true; do sleep 1 ; done"
    volumes:
      - ./data/rest/:/opt
    ports:
        - "8000:8000"
   