# Generated by Django 4.0.4 on 2022-11-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('index', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
