# Generated by Django 4.0.4 on 2022-11-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
